apiVersion: v1
kind: Namespace
metadata:
  name: svc-field
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: svc-field
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: nginx
        image: nginx