apiVersion: v1
kind: Pod
metadata:
  name: bar
spec:
  containers:
  - name: count
    image: quay.io/quay/busybox
    command: ["sh", "-c"]
    args: ['echo "unable-to-access-website" && i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 10; done']