apiVersion: v1
kind: Namespace
metadata:
  name: sidecar-field
---
apiVersion: v1
kind: Pod
metadata:
  name: big-corp-app
  namespace: sidecar-field
spec:
  volumes:
  - name: logs
    emptyDir: {}
  containers:
  - name: busybox
    image: busybox
    args: ["sh", "-c", "tail -n+1 -f /var/log/big-corp-app.log"]
    volumeMounts:
    - name: logs
      mountPath: /var/log
  - name: monitor
    image: busybox
    command: ["sh", "-c"]
    args: ["while true; do echo $(date) >> /var/log/big-corp-app.log; sleep 1; done"]
    volumeMounts:
      - mountPath: "/var/log"
        name: logs
