kind: Service
apiVersion: v1
metadata:
  name: service-am-i-ready
  namespace: default
  labels:
    id: cross-server-ready
spec:
  selector:
    id: cross-server-ready
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP