apiVersion: v1
kind: Pod
metadata:
  name: registry-test
  namespace: default
spec:
  containers:
    - name: registry-test-0
      image: registry.cka.com/library/busybox
      command: ["sh", "-c"]
      args: ["while true; do echo $(date); sleep 10; done"]
    - name: registry-test-1
      image: registry.cka.com/library/nginx